[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "pt"
  name = "pt"
  url = "pt"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "gallery"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "photo"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 5
    
[[main]]
  identifier = "notes"
  name = "notes"
  url = "notes"
  weight = 6